services:
  # app:
  #   build:
  #     context: app/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8051:8501"

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"